# Oral History as Data (OHD) - a Lib-STATIC Tool
# https://github.com/uidaholib/oral-history-as-data


##########
# Site settings
#
# title of site appears in banner
title: Tracing Race - Iowa State Library
# tagline appears in banner
tagline: Exploring the Journey of Asian Women in STEM at ISU
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Promoting gender equity within academia is an ongoing journey, and Iowa State University (ISU) is committed to creating an inclusive and diverse faculty community."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Mansi Patel
# Organization branding
organization-name: "Iowa State University"
organization-link: https://tracingrace.iastatedigital.org/asian-womeninstem-isu/
organization-logo-banner: https://cdil.lib.uidaho.edu/images/cdil-blacktransparent-logo.png
organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png


##########
# URL settings 
#
# url is your gh-pages base, following the pattern: username.github.io
# Leave this commented out unless you'd like to built the site somewhere other than GitHub pages. 
# In the latter case, see documentation here --> https://uidaholib.github.io/oral-history-as-data/advancedtopics.html#serve-the-site-from-another-location-not-github-pages
# url: 
# baseurl is your github repository's name prefixed with a /
# baseurl: 
# repository is the github repository's full url
repository: https://github.com/uidaholib/oral-history-as-data




####### Leave the Below As Is ########

# Jekyll collections settings
collections:
  transcripts:
    output: true
    permalink: /:collection/:name
  howto:
    output: true
    permalink: /:collection/:name
# defaults
defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
  - scope:
      type: howto
    values:
      layout: howto

# Build settings
markdown: kramdown



